foodmenu/food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    path('', views.index, name='index'),
    #path('<int:item_id>/', views.details, name='details'),
    path('<int:pk>/',views.FoodDetail.as_view(),name='details'),
    path('item/', views.item, name='item'),
    #add
    path('add',views.CreateItem.as_view(),name='create_item'),
    #path('add', views.create_item, name='create_item'),
    #edit
    path('update/<int:id>/', views.update_item, name='update_item'),
    path('delete/<int:id>/', views.delete_item, name='delete_item'),
]

foodmenu/foodmenu/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_view
from django.contrib.auth import views as authentication_view
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_view.register, name='register'),
    path('login/', authentication_view.LoginView.as_view(template_name = 'users/login.html'), name='login'),
    path('logout/', authentication_view.LogoutView.as_view(template_name = 'users/logout.html'), name='logout'),
    path('profile/', user_view.profilepage, name='profile'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodmenu/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Item(models.Model):
    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_description = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg")

    # delete this afterwards
    def get_absolute_url(self):
           return reverse("food:details", kwargs={"pk": self.pk})

foodmenu/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpeg', upload_to='profile_picture')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

foodmenu/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_description', 'item_price', 'item_image']

foodmenu/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

foodmenu/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.
def index(request):
    item_list = Item.objects.all()
    #template = loader.get_template('food/index.html')
    context = {
        'item_list': item_list,
    }
    return render(request, 'food/index.html', context)
    #return HttpResponse(template.render(context, request))

#Another Way Class based view
class IndexClassView(ListView):
   model = Item
   templateName = 'food/index.html'
   context_object_name = 'item_name'


def item(request):
    return HttpResponse('this is an item view')

def details(request, item_id):
    item = Item.objects.get(pk=item_id)
    context ={
        'item' : item
    }
    return render(request, 'food/detail.html', context)

    #return HttpResponse('this is item id: %s' %item_id)
#class Based
class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'



class foodDetail(DetailView):
    model = item
    template_name = 'food/detail.html'

def create_item(request):
    # print(request)
    # breakpoint()
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-from.html', {'form' : form})

#Classbased View
# this is a class based view for create item
 
class CreateItem(CreateView):
    model = Item;
    fields = ['item_name','item_description','item_price','item_image']
    template_name='food/item-from.html'
 
    def form_valid(self,form):
        form.instance.user_name = self.request.user
 
        return super().form_valid(form)





def update_item(request, id):
    item = Item.objects.get(id =id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-from.html', {'form':form, 'item':item})


def delete_item(request, id):
    item = Item.objects.get(id = id)
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request, 'food/item-delete.html', {'item':item})




    

foodmenu/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm
import sys

# Create your views here.
def register(request):
    
    if request.method == 'POST':
        
        form = RegisterForm(request.POST)
        # if not form.is_valid():
        #     print(form.errors)
        #     breakpoint()
        if form.is_valid():  # Ensure form is valid before accessing cleaned_data
            username = form.cleaned_data.get('username')
            form.save()
            messages.success(request, f'Account created for {username}!')
            return redirect('login')  # Replace 'some-view-name' with your desired redirect target
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})

@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

foodmenu/food/templates/food/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="#">Hidden brand</a>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
              <li>
                {% if user.is_authenticated %}
                    <a class="nav-link" aria-disabled="true" href="{% url 'profile' %}">Profile</a>
                    <a class="nav-link" aria-disabled="true" href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a class="nav-link" aria-disabled="true" href="{% url 'login' %}">Login</a>
                {% endif %}
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tag }}">
            {{ message }}
        </div>
            
        {% endfor %}
      {% endif %}
    {% block body %}

    {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

foodmenu/food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container mt-3">
    <div class="row">
        <div class="col-md-6">
            <img height="400px" width="600px" src="{{ item.item_image }}" alt="">
        </div>
        <div class="col-md-6">
            <h1>{{ item.item_name }}</h1>
            <p>{{ item.item_description }}</p>
            <h4>Price: {{ item.item_price }}</h4>
            <a class="btn btn-outline-danger" href="{% url 'food:delete_item' item.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

foodmenu/food/templates/food/index.html
{% extends 'food/base.html' %}

{% block body %}
    <h1>This is Just a template</h1>
    <h5>Item List</h5>
    <a class="btn btn-outline-info" href="{% url 'food:create_item' %}">Create Item</a>
    {% for item in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="150px" width="300px" src="{{ item.item_image }}" alt="">
            </div>
            <div class="col-md-4">
                <h3><a href="{% url 'food:details' item.id %}">{{ item.item_name }}</a></h3>
                <p>{{ item.item_description }}</p>
                <p>Price: {{ item.item_price }}</p>
            </div>
            <div class="col-md-2">
                <a class="btn btn-outline-success" href="{% url 'food:details' item.id %}">View Details</a>
                <a class="btn btn-outline-warning" href="{% url 'food:update_item' item.id %}">Update</a>
            </div>
        </div>
  
    {% endfor %}

{% endblock %}
   

 

foodmenu/food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

foodmenu/food/templates/food/item-from.html
{% extends 'food/base.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Save</button>
</form>

{% endblock %}

foodmenu/users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group form-control mb-2">
                                {{ field.name }}
                                {{ field }}
                            </div>
                        {% endfor %}
                        
                        <button class="form-control btn-outline-info" type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

foodmenu/users/templates/users/logout.html
<h1>You have been logged out</h1>

foodmenu/users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img src="{{ user.profile.image.url }}" alt="">

foodmenu/users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Sign Up
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group form-control mb-2">
                                {{ field.name }}
                                {{ field }}
                            </div>
                        {% endfor %}
                        
                        <button class="form-control btn-outline-info" type="submit">Sign Up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}